M48
; DRILL file {KiCad 8.0.6} date 2025-06-27T19:48:39+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-27T19:48:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1570
%
G90
G05
T1
X4.5244Y-2.2275
X4.5244Y-2.6275
T2
X4.6244Y-2.2775
X4.7244Y-2.5275
T3
X4.5244Y-2.4275
M30
