M48
; DRILL file {KiCad 8.0.6} date 2025-06-28T12:59:52+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-28T12:59:52+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1570
%
G90
G05
T1
X4.0416Y-2.3
X4.0416Y-2.7
X4.8033Y-2.3
X4.8033Y-2.7
T2
X4.1416Y-2.35
X4.2416Y-2.6
X4.9033Y-2.35
X5.0033Y-2.6
T3
X4.0416Y-2.5
X4.8033Y-2.5
M30
